use sells;
load data local infile '/home/oliver/rapnet_data/Rapnet_20130301_Main.csv' into table sells_tmp
fields terminated by ',' enclosed by '"' escaped by '\\'
ignore 1 lines
(             
Seller,
SellerId,
SellerCode,
Shape,
Weight,
Color,
FancyColor,
FancyIntensity,
FancyOvertone,
Clarity,
CutGrade,
Polish,
Symmetry,
FluorescenceColor,
FluorescenceIntensity,
Fluorescence,
Measurements,
MeasLength,
MeasWidth,
MeasDepth,
Ratio,
Lab,
CertNum,
StockNum,
Treatment,
Price,
DiscountPrice,
CashPrice,
CashDiscountPct,
CashTotalPrice,
Availability,
DepthPct,
TablePct,
Girdle,
GirdleMin,
GirdleMax,
Culet,
CuletSize,
CuletCondition,
CrownHeight,
PavilionDepth,
Comment,
City,
State,
Country,
IsMatchedPairSeparable,
PairStockNum,
ParcelNumStones,
CertificateURL,
LotNum,
RecordDate
)
set RecordDate = str_to_date(@dateVal, '%m/%d/%Y %h:%i:%s %p');