
SELECT ItemMaster.ItemNo AS StockNum, 
ItemMaster.CertNo AS CertNum, 
CASE WHEN Inventory.WorkCenter = 'DiaStock' THEN 'G' ELSE 'M' END AS Available,
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ItemMaster.DiamondShape,'B','A'),'CMB','C'),'R','BR'),'N','R'),'OE','EU'),'Q','PR'),'RM','BR'),'SPRE','SQE'),'AG','BAG'),'CMA','CUX'),'MMA','MQB'),'BBR','BR'),'SPRBR','CCSMB'),'TBR','TRILL') AS Shape,
ROUND(ItemMaster.SizeNominal,2) AS Size, 
CASE WHEN ItemMaster.UM1 IS NULL THEN ItemMaster.DiamondColor ELSE '' END AS Color, 
ItemMaster.DiamondQuality AS Clarity, 
REPLACE(REPLACE(REPLACE(REPLACE(ItemMaster.DiamondPolish,'GD','G'),'FA','F'),'FR','F'),'PR','P') AS Polish,
REPLACE(REPLACE(REPLACE(REPLACE(ItemMaster.DiamondSymmetry,'GD','G'),'FA','F'),'FR','F'),'PR','P') AS Symmetry,
REPLACE(REPLACE(REPLACE(REPLACE(ItemMaster.DiamondCutGrade,'GD','G'),'FA','F'),'FR','F'),'PR','P') AS CutGrade,
REPLACE(REPLACE(ItemMaster.DiamondFluor,'NN','N'),'FT','F') AS Fluor,
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ItemMaster.DiamondFluorColor,'Blue','B'),'White','W'),'Yellow','Y'),'Orange','O'),'Red','R'),'Green','G') AS FluorColor, 
ItemMaster.StoneSize AS Measurements,
REPLACE(ItemMaster.CertAgency,'EGL','EGU') AS Lab,
ItemMaster.WholesalePerUnitSell AS RapnetPrice,
ItemMaster.DiamondDepthPct AS DepthPercent,
ItemMaster.DiamondTablePct AS TablePercent,
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ItemMaster.DiamondGirdle,'ET','ETK'),'TH','THK'),'TN','THN'),'V','ETN'),'ME','MED'),'ETNT','VTK'),'ST','STK'),'ETNN','VTN') AS GirdleThin, 
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ItemMaster.DiamondGirdleTo,'ET','ETK'),'TH','THK'),'TN','THN'),'V','ETN'),'ME','MED'),'ETNT','VTK'),'ST','STK'),'ETNN','VTN') AS GirdleThick,  
REPLACE(REPLACE(REPLACE(REPLACE(ItemMaster.DiamondCulet,'NO','N'),'SM','S'),'MD','M'),'LG','L') AS CuletSize, 
'USA' AS CountryLoc,
'New York' AS StateLoc,
'New York' AS CityLoc,
'Y' AS RaplinkFeed,
'Y' AS MatchedPairSeparable,
REPLACE(REPLACE(ItemMaster.UM1, '<div>',''),'</div>','') AS FancyColor,
REPLACE(REPLACE(ItemMaster.UM2, '<div>',''),'</div>','') AS FancyColorIntensity,
REPLACE(REPLACE(ItemMaster.UM3, '<div>',''),'</div>','') AS FancyColorOverTone,
ItemMaster.UCBO2 AS Treatment
FROM ItemMaster INNER JOIN Inventory ON ItemMaster.ItemNo = Inventory.ItemNo
WHERE (ItemMaster.Type = 'CD') AND (Inventory.Quantity =1) AND ((LEFT(ItemMaster.CertNo,2) = 'US') OR (LEFT(ItemMaster.CertNo,1) IN ('0','1','2','3','4','5','6','7','8','9'))) AND NOT (Inventory.WorkCenter IN ('WPJapan','Alexand1','MWIEloq1','EGL1','GIA1','C00149','C00143','Recut1')) AND NOT (ItemMaster.WholesalePerUnitSell IS NULL)